### ISSUE TITLE
ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by mikehomee** [phunt/zookeeper_dashboard#10]
I'm sorry for being noob. But I need help. Please....

Traceback (most recent call last):
  File "./manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: No module named django.core.management

**Comment by mikehomee** [comment]
I installed django on my ubuntu 14.04 desktop. now my error is

Traceback (most recent call last):
  File "./manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager

**Comment by phunt** [comment]
Hi @mikehomee - I'm afraid I haven't been working on this of late - very likely that the latest django has moved on and my code doesn't work with it. Please take a look at this pull request. I haven't been able to merge it yet but it might help solve the issues you're seeing - the submitter has been working to get the project "refreshed". Good luck.

https://github.com/phunt/zookeeper_dashboard/pull/9

**Comment by mikehomee** [comment]
Thanks @phunt!

**Comment by phunt** [comment]
No problem.

**Comment by rohit-tm** [comment]
HI @mikehomee ....first of all you have to install "sudo apt-get install libzookeeper-dev".
then create zookeeper_dashboard inside zookeeper_dashboard_master.
fire below commands:
unzip zookeeper_dashboard.zip
cd zookeeper_dashboard-master
mkdir zookeeper_dashboard
mv \* zookeeper_dashboard
mv zookeeper_dashboard/manage.py ./

change inside .manage.py with 
import os,sys 
if **name** == "**main**":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "zookeeper_dashboard.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)

Setting.py

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',

# 'django.template.loaders.eggs.load_template_source',

)

Installed apps:
 'django.contrib.staticfiles', 

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "media/css"),
)
STATIC_URL = '/css/'

urls.py

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': './css'}),
    )

go with that procedure you have to run django and your monitoring will be start
