### ISSUE TITLE
settings.xml is missing

### ISSUE THREAD

**Issue by AGirin** [phunt/zookeeper_dashboard#7]
Hi!

I am reading documentation and it states that we need to modify settings.xml file to configure dashboard. I cannot find this file anywhere in zookeeper_dashboard path. 

Could you point me in the right direction?

Thanks,

Andrew

**Comment by phunt** [comment]
Thanks for the ping (just back from vacation), I think I meant settings.py (in the toplevel dir). I've updated the README.

Regards, 

Patrick
